[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.metadata.crane]
name = "grt"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"
license = "MIT"
repository = "https://github.com/smooney/grt"
description = "CLI/TUI tool for Git and Gerrit workflows"
