[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

# aarch64-unknown-linux-musl will be added here when that target is introduced

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-gcc"    # provided by cargo-zigbuild via Zig
